### ISSUE TITLE
1.adımda hata alıyorum.

### ISSUE THREAD

**Issue by ezelhandikmenli** [alaturka/windows#10]
### Adım

1 (ön kurulum)

### Hata ekranı

![Hata Ekranı](https://user-images.githubusercontent.com/72813315/157295053-65a4af8a-126b-4c95-a1b7-7387e71d2d2d.jpg)

### Windows sürümü

```text
Edisyon: Windows 10 Pro
Sürüm:2004
Yüklenme Tarihi:8.09.2020
İS derlemesi:19041.1415
Deneyim: Windows Feature Experience Pack 
         120.2212.3920.0
```

### Ayrıntılar

Merhaba hocam , 1. aşamadayken bu tür hatalar alıyorum ne yapmam gerekir ?

**Comment by roktas** [comment]
Kurulumun ilk adımını aşağıdaki komutla dener misin?  Aldığın hata ekranını hata kaydına yapıştır.

```ps1
$VerbosePreference = 'Continue'; Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force;
iwr -useb https://get.classroom.alaturka.dev/classroom | iex
```

**Comment by ezelhandikmenli** [comment]
![Hata Goruntusu](https://user-images.githubusercontent.com/72813315/157321289-3fdf0c1e-0488-4100-8dc5-cae3fa51b331.jpg)

**Comment by ezelhandikmenli** [comment]
![Hata2](https://user-images.githubusercontent.com/72813315/157416067-161c8466-4f86-45eb-b7c9-42d42c9c1eb6.jpg)

**Comment by ezelhandikmenli** [comment]
Hocam sizin en son verdiğiniz komutu yazdığımda böyle bir durumla karşılaştım ne yapmalıyım ?

**Comment by roktas** [comment]
ScoopInstaller'da değişiklik yapmışlar, sorunun nedeni bu.  Düzeltme yayınladım, kurulumu tekrar et.

**Comment by ezelhandikmenli** [comment]
Hocam birçok kez denedim fakat her defasında aynı hatayı alıyorum. Ne yapmam gerekir ?

**Comment by roktas** [comment]
Robocopy sisteminde kurulmamış gözüküyor.  Bu program Windows'da standart geliyor olmalı.  Nedenini inceleyeceğim.

**Comment by roktas** [comment]
Bu sorun için yararı olur mu bilmiyorum ama (başka bir sorunu adresleyen) bir düzeltme yayınladım.  Tercihen makineyi yeniden başlat ve sonrasında aşağıdaki komutlarla kurulumu tekrar dene:

```ps1
$Env:CLASSROOM_BOOTSTRAP_AFRESH="true"; Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force; iwr -useb https://get.classroom.alaturka.dev/classroom | iex
```

Hala Robocopy hatası alıyorsan bu başka bir sorun; kurulum programıyla bir ilgisi yok, Robocop ya yüklü değil (bu biraz tuhaf) ya da Path'e ekli değil.

**Comment by ezelhandikmenli** [comment]
Hocam gönderdiğiniz komutu birkaç kez denedim fakat  sürekli aynı hatayı alıyorum.

**Comment by roktas** [comment]
@ezelhandikmenli Sorun devam ediyorsa hata raporunu kapatma lütfen, takip etmemiz zorlaştırıyorsunuz sorunu.

**Comment by roktas** [comment]
Powershell yönetici terminali açarak aşağıdaki komutları çalıştır ve  ekran görüntüsü ekle

```ps1
$Env:PATH
ls \Windows\System32\Robo*
```

**Comment by ezelhandikmenli** [comment]
![Robo](https://user-images.githubusercontent.com/72813315/157444000-ab143176-65c4-4da8-9c76-98b2e1d4f1de.jpg)

**Comment by roktas** [comment]
`$Env:PATH` ?

**Comment by roktas** [comment]
@ezelhandikmenli sana görev:  PATH değişkeninin ne olduğunu öğren ve **yönetici powershell terminalinde** bunu nasıl görüntüleyeceğini araştır.  sonra buraya gel ve sonucu yaz.

**Comment by ezelhandikmenli** [comment]
Hocam PATH değişkeninin içerisinde bulunan dosya yollarına kısayol oluşturduğunu anladım. Yönetici powershell termalinde $Env:Path ile PATH içeriğini görebiliyorum. En son aldığım hatada bu cümleyi gördüm.

`Scoop required 'C:\Windows\System32\Robocopy.exe' to work. Please make sure 'C:\Windows\System32' is in your PATH.`

Bu cümlede PATH içeriğinde 'C:\Windows\System32' yolunun bulunmasından emin olmamı istediğini gördüm. Ardından Bilgisayar->Özellikler->Gelişmiş Sistem Ayarları->Ortam Değişkenleri yoluyla PATH içeriğine bu yolu ekledim. Sonra kurulumu en baştan yaptım. Başarılı bir şekilde kurdum. Yardımlarınız için çok teşekkür ederim.
