### ISSUE TITLE
ön kurulum sorunu

### ISSUE THREAD

**Issue by yagmurgul** [alaturka/windows#11]
### Adım

1 (ön kurulum)

### Hata ekranı

![cls](https://user-images.githubusercontent.com/91977186/157323603-6b4bc0fa-40d2-457b-b1f2-4d81d4985dda.png)

### Windows sürümü

```text
İşlemci	Intel(R) Pentium(R) CPU  N3520  @ 2.16GHz   2.16 GHz
Takılı RAM	4,00 GB (kullanılabilir: 3,89 GB)

Sistem türü	64 bit işletim sistemi, x64 tabanlı işlemci
```

### Ayrıntılar

hocam dün ön kurulumdan sonra yeniden başlatırken mavi ekran vermişti. Bugün tekrar kurulum yaparken böyle bir hata alıyorum.

**Comment by roktas** [comment]
@yagmurgul hatayı ilgisizi bir yere yazmışsın (sildim) 

![image](https://user-images.githubusercontent.com/47842/157328627-e672edff-90c8-4bb1-a550-4b999f84196a.png)

Lütfen doğru kanalları kullanalım, panik yok.  Bir düzenleme üzerinde çalışıyorum, biraz bekle.

**Comment by roktas** [comment]
Aşağıdaki komutu kullanarak **ön** kurulum yap

```ps1
$Env:CLASSROOM_BOOTSTRAP_AFRESH="true"; Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force;
iwr -useb https://get.classroom.alaturka.dev/classroom | iex
```

(Ön kurulum başarılıysa ikinci aşama dokümanlarda yazdığı gibi: `classroom install`)
