### ISSUE TITLE
hata

### ISSUE THREAD

**Issue by yagmurgul** [alaturka/windows#13]
### Adım

1 (ön kurulum)

### Hata ekranı

![1,](https://user-images.githubusercontent.com/91977186/157395280-53ca6a83-37de-4fee-b053-1e3f8ae9aef5.png)
![2,](https://user-images.githubusercontent.com/91977186/157395284-859a3d26-aead-4781-b3bc-660870eade4a.png)

### Windows sürümü

```text
Edisyon	Windows 10 Home
Sürüm	20H2
Yüklenme tarihi	‎19.‎09.‎2021
İS derlemesi	19042.1466
Deneyim	Windows Feature Experience Pack 120.2212.3920.0
```

### Ayrıntılar

Hocam bana attıgınız kodu yazarak ön kurulumu bastan yapmayı denedim. 1. fotograftaki gibi hata aldım. Tekrar denedigimde de dosya baska islemde kullanıldıgından o asamaya gelemeden hata verdi. Ne yapmam gerekiyor ?

**Comment by roktas** [comment]
@yagmurgul Her sorun için ayrı bir iş kaydı açma lütfen, işimizi zorlaştırıyor bu.  Bak önceki kayıt #11 zaten duruyordu, niye onun altına yazmadın?  Neyse, o kaydı kapatıyorum; bundan sonra bu kayıt altında devam etsin.

Sorununu inceleyeceğim.

**Comment by roktas** [comment]
ScoopInstaller'da değişiklik yapmışlar, sorunun temel nedeni bu.  Düzeltme yayınladım, kurulumu tekrar et.

**Comment by yagmurgul** [comment]
Hocam ön kurulumu tekrar yaparken yukarıda attığım 2. fotoğraftaki gibi code fontun baska bir islemde kullanıldıgına dair hata verdi.  Birkaç dakika sonra da mavi ekranda kilitleniyor yazısı çıktı ve bilgisayar kilitlendi. İnternetten araştırdım biraz bios pili söküp takmak gibi seyler yazmıslar ama ne yapmam gerekiyor

**Comment by roktas** [comment]
Hata iletisinde görülen `Cascadia Code` font sorunu için bir düzeltme yayınladım (`$Date: 09-03-2022 14:07:15$`).  Kurulumu tekrar et, o sorunun artık olmaması lazım. 

Öte yandan aldığın mavi ekrar hatası hakkında...  Sisteminin belleği çok düşük 4 GB, sınır bir değer.  Ayrıca fiziksel olarak da sorunlar var gibime geliyor (RAM hatası vb).  En kısa zamanda RAM'ları kontrol ettir + sisteme ilave RAM al (8 GB'a çıkar).

**Comment by roktas** [comment]
Bu sorun kurulum programındaki bir hataya karşı düşmediğinden kapatıyorum.
