### ISSUE TITLE
Yönetici olarak çalıştır hatası alıyorum.

### ISSUE THREAD

**Issue by mustafacetin19** [alaturka/windows#14]
### Adım

1 (ön kurulum)

### Hata ekranı

Running the installer as administrator is disabled by default, use -RunAsAdmin parameter if you know what you are doing.

### Windows sürümü

```text
Cihaz adı	DESKTOP-5PQ8CFJ
İşlemci	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
Takılı RAM	16,0 GB (kullanılabilir: 15,8 GB)
Cihaz Kimliği	FCBE8D95-993B-4CD2-93A3-89A2DC5396EF
Sistem türü	64 bit işletim sistemi, x64 tabanlı işlemci
Kalem ve dokunma	Bu görüntü biriminde kalem girdisi veya dokunarak giriş yok
```

### Ayrıntılar

Yönetici olarak çalıştırdığım halde bu hatayı alıyorum.

**Comment by roktas** [comment]
ScoopInstaller'da değişiklik yapmışlar, sorunun nedeni bu.  Düzeltme yayınladım, kurulumu tekrar et.

**Comment by mustafacetin19** [comment]
![2](https://user-images.githubusercontent.com/72816472/157421502-0ce43e7b-1f80-4774-879a-4bdaa1b9210c.png)
Şu anda da bu hatayı alıyorum diğer sorun paylaşanlarda cevap olarak ScoopInstaller da değişiklik olduğu yanıtını vermişsiniz bir süre kurulum yapmadan beklemeli miyim? İlginiz için teşekkürler.

**Comment by roktas** [comment]
Evet bir süre bekledikten sonra kurulumu tekrar et.

**Comment by roktas** [comment]
@BunyaminAkdeniz ile bir deneme yaptık.  Kullanıcı adında Türkçe karakter (ve boşluk) kullandığından scoop paket yöneticisi bir adımda hata veriyor.  Bunun çabuk bir çözümü yok maalesef, hata bizim dışımızda ve Scoop'a bir düzeltme yapmak gerekiyor.  Bu durumda ne yapacaksınız?  Türkçe karakter ve boşluk içermeyecek şekilde bir kullanıcı adı seçerek yeniden Windows kurulumu yapın.  (Alternatif yöntemler, ör. kullanıcı adını değiştirmek vs sıkıntılı bir süreç olduğundan bunu öneriyorum.).  Tavsiyem Github kullanıcı adınız neyse onu kullanmanız.  İş kaydını şimilik kapatıyorum.
