### ISSUE TITLE
Birinci Aşama: Önyükleme Hatası

### ISSUE THREAD

**Issue by zeynepsila** [alaturka/windows#15]
### Adım

1 (ön kurulum)

### Hata ekranı

![Ekran görüntüsü 2022-03-09 141337](https://user-images.githubusercontent.com/72812386/157431776-c4089f38-116a-4ff1-af54-f70a25e08084.png)

### Windows sürümü

```text
Edisyon	Windows 11 Home Single Language
Sürüm	21H2
Yüklenme tarihi	‎5.‎03.‎2022
İS derlemesi	22000.493
Seri numarası	PF2XPE70
Deneyim	Windows Özelliği Deneyim Paketi 1000.22000.493.0
```

### Ayrıntılar

Hocam merhaba, birinci aşama: önyükleme bölümünde böyle bir hata alıyorum. Ne yapabillirim?

**Comment by roktas** [comment]
@zeynepsila Kurulumu farklı zaman ve ortamlarda bir kaç kez daha dene.  Hala devam ediyorsa tahminlerim şöyle:

Kullanıcı adını içinde boşluk (ve Türkçe karakter) olacak şekilde `Zeynep Sıla` yapmışsın, ev dizini de `C:\Users\Zeynep Sıla` haliyle içinde boşluk karakteri olan bir klasör.  Emin değilim ama bu bir sorun olabilir (Git rahatsız oluyor).  Windows'da kullanıcı adını içinde boşluk ve Türkçe karakter içermeyecek şekilde değiştirmeyi dene (ör. `zeynepsila` verebilirsin).  Bunu nasıl yapabileceğini bilmiyorum, araştırmalısın.

**Comment by zeynepsila** [comment]
İlk başta başka bir adımda hata alıyordum ama kurulumu farklı zamanda yaptığımda aldığım hata değişmişti, dediğiniz gibi başka bir zamanda yine denerim. Kullanıcı adımı da değiştirmeyi deneyeceğim. Cevabınız için teşekkür ederim.

**Comment by roktas** [comment]
@BunyaminAkdeniz ile bir deneme yaptık.  Kullanıcı adında Türkçe karakter (ve boşluk) kullandığından scoop paket yöneticisi bir adımda hata veriyor.  Bunun çabuk bir çözümü yok maalesef, hata bizim dışımızda ve Scoop'a bir düzeltme yapmak gerekiyor.  Bu durumda ne yapacaksınız?  Türkçe karakter ve boşluk içermeyecek şekilde bir kullanıcı adı seçerek yeniden Windows kurulumu yapın.  (Alternatif yöntemler, ör. kullanıcı adını değiştirmek vs sıkıntılı bir süreç olduğundan bunu öneriyorum.).  Tavsiyem Github kullanıcı adınız neyse onu kullanmanız.  İş kaydını şimilik kapatıyorum.

**Comment by zeynepsila** [comment]
Hocam dediklerinizi uyguladım ve classroom ortamı başarılı bir şekilde kuruldu. Yardımlarınız için teşekkür ederim.
