### ISSUE TITLE
İkinci Aşama: Kurulum

### ISSUE THREAD

**Issue by esracum** [alaturka/windows#16]
### Adım

3 (makine yeniden başlatıldıktan sonra yapılan son kurulum)

### Hata ekranı

![Ekran Görüntüsü (350)](https://user-images.githubusercontent.com/91957149/157468014-f45c74eb-7407-4f75-86b0-6a8573a1b26f.png)

### Windows sürümü

```text
Cihaz adı	esracum
İşlemci	Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.19 GHz
Takılı RAM	8,00 GB (kullanılabilir: 7,70 GB)
Cihaz Kimliği	6A3D8729-0042-45EB-A5A5-B15565B859FB
Sistem türü	64 bit işletim sistemi, x64 tabanlı işlemci
Kalem ve dokunma	Bu görüntü biriminde kalem girdisi veya dokunarak giriş yok
```

### Kurulum sayısı

- [ ] Evet, en az bir defa tekrar ettim
- [X] Evet, birden fazla defa tekrar ettim
- [ ] Hayır, tekrar deneme yapmadım (lütfen bu noktada durup kurulumu tekrar edin)

**Comment by roktas** [comment]
@esracum Kurulum talimatlarına dikkat ettin mi?  İkinci aşama kurulum için Powershell terminali değil Windows Terminalini kullanacaksın: [Ekran animasyonu bile verilmiş](https://classroom.alaturka.dev/intro/install.html#ikinci-asama-kurulum)

**Comment by esracum** [comment]
Evet hocam, ona özellikle dikkat ettim ve rehber animasyona da defalarca baktım. Hocam, ilk seferki denemem de dahil her seferinde arama bölümüne "Windows Terminali" yazdım ve oradan devam ettim. Yine aynı hatayı alıyorum. Nereyi atlıyorum anlamadım.

**Comment by roktas** [comment]
Bu hatayı reproduce edemiyorum.  İlk aşama kurulumda gözünden kaçan bir sorun olmuş olabilir mi?  Örneğin bak bu hata da öyle: #17

Herhangi bir şeye dokunmadan ilk aşamayı al baştan yapar mısın (Yönetici Powershell terminalinde)?

```ps1
$VerbosePreference = 'Continue'; Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force; iwr -useb https://get.classroom.alaturka.dev/classroom | iex
```

**Comment by esracum** [comment]
Teşekkür ederim hocam, halloldu. İyi akşamlar.
