### ISSUE TITLE
Kurulum bitti

### ISSUE THREAD

**Issue by furkan-yusuf** [alaturka/windows#18]
### Adım

3 (makine yeniden başlatıldıktan sonra yapılan son kurulum)

### Hata ekranı

![hata](https://user-images.githubusercontent.com/91973834/157500174-00f73cf5-74c5-405f-9458-458942ebfa67.jpeg)
![diğer foto](https://user-images.githubusercontent.com/91973834/157500511-c5e2097f-c6f1-4d0b-bcd0-4e120f5cb85c.jpeg)

### Windows sürümü

```text
Edisyon	Windows 10 Home
Sürüm	21H2
Yüklenme tarihi	‎3.‎03.‎2022
İS derlemesi	19044.1288
Deneyim	Windows Feature Experience Pack 120.2212.3920.0
```

### Kurulum sayısı

- [X] Evet, en az bir defa tekrar ettim
- [ ] Evet, birden fazla defa tekrar ettim
- [ ] Hayır, tekrar deneme yapmadım (lütfen bu noktada durup kurulumu tekrar edin)

### Ayrıntılar

hocam kurulumda bir sorun yaşamadım söylediğiniz gibi yaptım ama vs code da kodu çalıştırdığım zaman böyle bir hata alıyorum. Uğraştım çözmek için ama yapamadım

**Comment by roktas** [comment]
C geliştirme ortamı Windows tarafında değil Linux tarafında kurulu.  Terminali de o tarafta açacaksın.  Terminal seçeneklerini incele ve WSL terminalini çalıştır.

**Comment by roktas** [comment]
@furkan-yusuf Şimdilik bununla uğraşma.  Dokümante edeceğim bir konu bu.  Biraz bekle, dokümanı çıktığında bakarsın.

**Comment by roktas** [comment]
Kurulum programında bir hataya karşı düşmediğinden iş kaydını kapatıyorum.  Konu hakkında doküman yayınlayacağım.

**Comment by roktas** [comment]
@furkan-yusuf Doküman hazır: https://classroom.alaturka.dev/guide/#vs-code-ile-classroom-icinde-gelistirme
