### ISSUE TITLE
vs code hatası 

### ISSUE THREAD

**Issue by sekcfc** [alaturka/windows#19]
### Adım

3 (makine yeniden başlatıldıktan sonra yapılan son kurulum)

### Hata ekranı

![image](https://user-images.githubusercontent.com/77936492/157517455-503fde11-01c7-4ff3-b9c9-b4c9d9c1152d.png)

### Windows sürümü

```text
Edisyon	Windows 11 Pro
Sürüm	21H2
Yüklenme tarihi	‎8.‎11.‎2021
İS derlemesi	22000.493
Deneyim	Windows Özelliği Deneyim Paketi 1000.22000.493.0
```

### Kurulum sayısı

- [ ] Evet, en az bir defa tekrar ettim
- [X] Evet, birden fazla defa tekrar ettim
- [ ] Hayır, tekrar deneme yapmadım (lütfen bu noktada durup kurulumu tekrar edin)

### Ayrıntılar

Hocam kusura bakmayın. Son adımda, Vs code u önceden kurduğum için bu hatayı alıyor olabilir miyim ? Eğer bundan dolayıysa ne yapmam gerekir

**Comment by roktas** [comment]
İlk aşama kurulumunda sorun var hala.  [Tekrar et](https://classroom.alaturka.dev/intro/install.html#birinci-asama-onyukleme)

**Comment by roktas** [comment]
@sekcfc dönüş bekliyorum.

**Comment by sekcfc** [comment]
ilk kurulumu tekrar denedim ve başarıyla yüklendi ama 2. kurulumda sonucu aynı oldu. İnternet kaynaklı olduğunu düşünüp farklı bir ağda denedim fakat yine aynı hatayı aldım. Şimdi vscode u kaldırdığımdan tamamen emin olarak tekrar deneyeceğim.

**Comment by roktas** [comment]
Şöyle yapalım:

```ps1
scoop bucket rm extras
scoop bucket add extras
classroom -Verbose install
```

**Comment by sekcfc** [comment]
İnternet yavaşlığından dolayı bir önceki hala sürüyor, olmazsa bunu deneyeceğim sonrasında.

**Comment by sekcfc** [comment]
Bunu denedim oldu devam ediyor şu an.

**Comment by sekcfc** [comment]
oldu hocam teşekkür ederim

**Comment by roktas** [comment]
👍
