### ISSUE TITLE
Windows Terminal indirilemiyor.

### ISSUE THREAD

**Issue by ahmet-talha-asliyuce** [alaturka/windows#2]
### Adım

1 (ön kurulum)

### Hata ekranı

![windows-terminal](https://user-images.githubusercontent.com/91966325/156729618-1f5cf4b5-94b8-4212-be83-fd317a639cf3.png)

### Windows sürümü

```text
Edition	        Windows 10 Home
Version	        20H2
Installed on	‎11/‎28/‎2021
OS build	19042.1526
Experience	Windows Feature Experience Pack 120.2212.4170.0
```

### Ayrıntılar

Merhaba hocam, ağda sıkıntı yok ve birkaç kere denedim aynı hatayı veriyor.

**Comment by roktas** [comment]
Scoop `Extras` deposu eklenmemiş gibi.  Kurulumu yapacak gibi Terminal aç ve aşağıdaki komutun çıktısı yaz bakalım:

```ps1
scoop bucket list
```

**Comment by beyza-ozben** [comment]
Yönetici terminalde çalıştırdım ve çıktı şu şekilde:
classroom
extras
main
nerd-fonts

**Comment by roktas** [comment]
Extras depos ekli gözüküyor.  Şöyle yapalım:

```ps1
scoop bucket rm extras
scoop bucket add extras
scoop update
```

Sonrasında kurulumu tekrar edelim...

**Comment by beyza-ozben** [comment]
Aldığım hatanın çıktısı:

iwr : Temel alınan bağlantı kapatıldı: SSL/TLS güvenli kanalı içi güven ilişkisi kurulamadı.
At line:2 char:1
+ iwr -useb https://get.classroom.alaturka.dev/classroom | iex
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by beyza-ozben** [comment]
Önceki mesajdaki hatanın ağ problemi olduğunu fark ettim şimdi ise birinci aşama başarıyla yüklendi, teşekkür ediyorum
