### ISSUE TITLE
windows shell yükleme hatası

### ISSUE THREAD

**Issue by Esratass** [alaturka/windows#20]
### Adım

1 (ön kurulum)

### Hata ekranı

![image](https://user-images.githubusercontent.com/92054816/157528928-cd31045a-51b2-4b1d-93f8-41b7506ca617.png)
![image](https://user-images.githubusercontent.com/92054816/157529207-50402348-770f-41da-acf1-a734657a86e8.png)

### Windows sürümü

```text
Cihaz adı	DESKTOP-J3S7BBB
İşlemci	Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.19 GHz
Takılı RAM	8,00 GB (kullanılabilir: 7,81 GB)
Cihaz Kimliği	77FDA285-21AD-48C0-AE7D-CDA256815B0B
Ürün Kimliği	00331-10000-00001-AA944
Sistem türü	64 bit işletim sistemi, x64 tabanlı işlemci
Kalem ve dokunma	Bu görüntü biriminde kalem girdisi veya dokunarak giriş yok
```

### Kurulum sayısı

- [ ] Evet, en az bir defa tekrar ettim
- [X] Evet, birden fazla defa tekrar ettim
- [ ] Hayır, tekrar deneme yapmadım (lütfen bu noktada durup kurulumu tekrar edin)

### Ayrıntılar

yükleme yaparken 1. adım sonunda ''Y'' harfini yazmayı unuttum. işlemleri geri alamıyorum.

**Comment by roktas** [comment]
Classroom'u kurmuş gözüküyorsun, sorununu anlamadım.

**Comment by Esratass** [comment]
Anladım hocam. Yardımcı olduğunuz için çok teşekkürler.
