### ISSUE TITLE
Windows Terminal hatası

### ISSUE THREAD

**Issue by mssahin** [alaturka/windows#23]
### Adım

3 (makine yeniden başlatıldıktan sonra yapılan son kurulum)

### Hata ekranı

![image](https://user-images.githubusercontent.com/92573052/157828144-354746f9-f072-4c4f-88ae-0bb8ae1d7750.png)

### Windows sürümü

```text
Windows 10 Pro 
Sürüm 1909
```

### Kurulum sayısı

Evet, birden fazla kez tekrar ettim

### Ayrıntılar

Hocam, 1. aşamayı başarılı bir şekilde tamamladım. İkinci kurulumu başlatmak için windows terminali açtığımda "Failed to load settings" hatasını alıyorum. Tamam'a bastığımda Windows terminali kullanabiliyorum. 2. kurulumu başlatmadan önce ne yapmalıyım?

**Comment by roktas** [comment]
Bu farklı bir sorun , Windows Terminal ayarlarını bozacak bir şey yapmıyoruz.  Sorunlu Windows Terminal profilini bulup kaldırmaya çalış.  Sanıyorum bunu yapmasan bile kuruluma devam edebilirsin.

**Comment by mssahin** [comment]
Tamam Hocam. Windows terminal profillerine bakayım. Bir şey bulamazsam 2. kurulumu başlatırım sağolun.

**Comment by roktas** [comment]
https://superuser.com/questions/1660282/encountered-errors-while-loading-user-settings-in-windows-terminal-on-windows-11

**Comment by mssahin** [comment]
Verdiğiniz linkleri ayarları Windows terminal için yapıp kaydet tuşuna bastığımda yine aynı hatayı "Failed to reload settings"  alıyorum Hocam.

**Comment by roktas** [comment]
Powershell terminali açarak:
+
```ps1
scoop cache rm *; scoop uninstall windows-terminal
```

Bu noktada kontrol yapalım "Windows Terminal"in kalkmış olması lazım (kalkmamışsa sisteminde başka bir kaynaktan kurulum Windows Terminal var demektir, bunu bana raporlarsın)

```ps1
Remove-Item  "$HOME\AppData\Local\Microsoft\Windows Terminal' -Recurse -Force -Confirm:$false; scoop install windows-terminal
```

Böyle deneyelim... (Yazmak yerne copy/paste ile aktar)

**Comment by mssahin** [comment]
![image](https://user-images.githubusercontent.com/92573052/157854782-71f1cbc5-ff0b-4ecd-9842-16863c221bca.png)
Hocam powershell de verdiğiniz kodu çalıştırınca aldığım ekran çıktı bu şekilde. 
Bir de uygulamalardan baktığımda Windows terminal gözükmüyor.

**Comment by roktas** [comment]
Normal (yönetici olmayan) Powershell terminalinde ne oluyor?

**Comment by mssahin** [comment]
Onda da aynı hatayı alıyorum Hocam.

**Comment by roktas** [comment]
Terminal sorunundan çıktı bu :-)  İlk aşama kurulumunda sorun var gibi.  Birinci aşama kurulumu aşağıdaki komutla tekrar edip ekran görüntüsünü paylaşır mısın benimle? (Paylaştıktan sonra hata yoksa, yukarıdaki işlemleri yaparsın)

```ps1
$VerbosePreference = 'Continue'; Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force;
iwr -useb https://get.classroom.alaturka.dev/classroom | iex
```

**Comment by mssahin** [comment]
Tamam Hocam şuan başladı kurulumlar tek tek. Tamamlanınca durum hakkında bilgi vereceğim.

**Comment by mssahin** [comment]
![image](https://user-images.githubusercontent.com/92573052/157865135-94cb8a25-9a00-4bb0-ac79-57335102e06d.png)
Hatasız bir şekilde tamamlandı Hocam devam ediyorum.

**Comment by roktas** [comment]
Sorun devam ederse birinci aşamayı tamamen sıfırdan yaparsın:

```ps1
$Env:CLASSROOM_BOOTSTRAP_AFRESH="true"; $VerbosePreference='Continue'; Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force; iwr -useb https://get.classroom.alaturka.dev/classroom | iex
```

**Comment by roktas** [comment]
Başarı ölçüsü şu ekranı almaman:

![image](https://user-images.githubusercontent.com/47842/157865506-10831a4b-165a-45d3-a7bd-b6ad70370af3.png)

**Comment by mssahin** [comment]
![image](https://user-images.githubusercontent.com/92573052/157865833-02f7710d-3bbe-44fc-b2aa-00c071f543de.png)
Windows terminal başarılı bir şekilde kaldırıldı Hocam

**Comment by mssahin** [comment]
Şimdi daha önce verdiğiniz kodu 
Remove-Item  "$HOME\AppData\Local\Microsoft\Windows Terminal' -Recurse -Force -Confirm:$false; scoop install windows-terminal
çalıştıracağım.
