### ISSUE TITLE
Windows terminal açma sorunu

### ISSUE THREAD

**Issue by siyambashavva** [alaturka/windows#24]
### Adım

3 (makine yeniden başlatıldıktan sonra yapılan son kurulum)

### Hata ekranı

![Adsız](https://user-images.githubusercontent.com/92372517/157879049-268ec753-6aa3-4c40-90e1-94ee9ab62ad2.png)

### Windows sürümü

```text
Edisyon	Windows 10 Pro
Sürüm	20H2
Yüklenme tarihi	‎19.‎08.‎2021
İS derlemesi	19042.1526
Deneyim	Windows Feature Experience Pack 120.2212.4170.0
```

### Kurulum sayısı

Evet, birden fazla kez tekrar ettim

### Kurulum Yardımı

Evet okudum, sorunum farklı: https://classroom.alaturka.dev/help/install.html

### Ayrıntılar

Ön kurulumun tamamlanmasına rağmen windows terminal hiç açılmadı.  Classroom ortamın kurulumunu tekrar yapmaya çalıştığımda powershell ' de herhangi bir işlem yapılamadı uyarısı ile karşılaştım.

**Comment by roktas** [comment]
> Classroom ortamın kurulumunu tekrar yapmaya çalıştığımda powershell ' de herhangi bir işlem yapılamadı uyarısı ile karşılaştım.

Bunu yazmak yerine ekran görüntüsü paylaşır mısın?

**Comment by roktas** [comment]
Powershell terminali aç ve şu komutları çalıştır:

```ps1
scoop cache rm *; scoop uninstall windows-terminal; scoop windows-terminal
```

Bu adımda hata alıyorsan ekran görüntüsü ekle (hata mesajı veya yorum yok, ekran görüntüsü istiyorum).  Sorun düzelmemişse başka bir şey deneyeceğiz.

**Comment by roktas** [comment]
@siyambashavva yukarıda verdiğim komutların sonucunda ortaya çıkan ekran görüntüsünü istiyorum (hatalı girdiyi sildim).

**Comment by siyambashavva** [comment]
![Adsız](https://user-images.githubusercontent.com/92372517/157889643-e087c669-cbff-4219-9996-71dd6ef78a89.png)

**Comment by roktas** [comment]
```ps1
scoop install windows-terminal
```

**Comment by siyambashavva** [comment]
![Adsız](https://user-images.githubusercontent.com/92372517/157891714-176fba86-5afd-44ba-897f-4f87dd5fc940.png)

**Comment by siyambashavva** [comment]
hocam tabii ki iyi ilerliyor ama yine de terminal açılmıyor.

**Comment by roktas** [comment]
Son ekran görüntüsü anlamlı değil, windows-terminali sildiğin halde hala kurulu gözüküyor.  (Düzeltilmiş haliyle) Tekrar et:

```ps1
scoop cache rm *; scoop uninstall windows-terminal; scoop install windows-terminal
```

Sorun hala devam ediyorsa bir de şu komutun çıktısını ekle:

```ps1
gcm windows-terminal
```

**Comment by roktas** [comment]
Bu da olmazsa şu dokümanlardaki talimatları uygula (3 yöntem verilmiş işe yarayıncaya kadar hepsini uygula).  Ama önce yukarıda yazdıklarımı yap.

https://aavtech.site/2020/09/solution-for-windows-terminal-not-starting/

**Comment by siyambashavva** [comment]
scoop cache rm *; scoop uninstall windows-terminal; scoop install windows-terminal
hocam bu komutu bugün powershellde yeniden denedim ve bu hatayı verdi.

**Comment by siyambashavva** [comment]
![sorun 1](https://user-images.githubusercontent.com/92372517/158011901-8e96496a-5835-4fd1-8b52-5b9f6986a404.png)

**Comment by roktas** [comment]
Ağ bağlantından (bulunduğun yerde) sorun var.  Aynı komut tekrar dene, hala devam ediyorsa bilgisayar labında dene.

**Comment by siyambashavva** [comment]
Hocam yurtta internet çok yavaş farklı bir yerde deneyeceğim.

**Comment by roktas** [comment]
@siyambashavva 4 gün geçmiş bu iş kaydının üzerinden.  Sonuç?

**Comment by siyambashavva** [comment]
Hocam yapamazsan bilgisayar labında yap demiştiniz sizinle konuştuktan hemen sonra pazar günü Gülcan hocaya mail atmıştım pazartesi yapabilir miyiz diye geri dönmedi bugün laba gideceğim. (bu arada not : hocam tam halletmeden size söylemek istemedim yoksa benimle ilgilenip sorunu çözmeye çalıştığınız için teşekkürler sonuçta böyle bir zorunluluğunuz yok ben her şeyi halledip size öyle teşekkür etmek istemiştim pazartesi günkü derse canlı katıldım ders başlamadan söylediğiniz çoğu şeyi üstüme alındım doğrusu( hocamızsınız sonuçta alınmadım tabii :) ).

**Comment by roktas** [comment]
@siyambashavva üzerine alınmanız için konuştum zaten :-)

**Comment by siyambashavva** [comment]
Hocam windows terminali labda kurdum ama terminal açıldığında hata veriyor aynı zamanda vs code da terminali açamıyorum aşağıdaki hataları alıyorum.
![Ekran görüntüsü 2022-03-16 152409](https://user-images.githubusercontent.com/92372517/158589557-66b67ba1-24fa-40b6-a2fa-678e92e52ee9.png)
![Ekran görüntüsü 2022-03-16 152330](https://user-images.githubusercontent.com/92372517/158589566-0aea5da2-9a9e-4933-989e-d9650fe4232b.png)
.

**Comment by roktas** [comment]
[Geriye tek denenecek seçenek bu gözüküyor](https://classroom.alaturka.dev/help/install.html#onerilen-tum-cozum-yontemlerini-denedim-fakat-kurulum-bir-turlu-basar%C4%B1l%C4%B1-olmuyor)

**Comment by siyambashavva** [comment]
Hocam aslında bilgisayar yeni çok uygulama da yüklemedim niye böyle oldu anlamadım bilgisayar  freedos gelmişti bilgisayar mühendisi bir yakınım yüklemişti Windows’u, daha önce denemediğim için  kaldırıp yeniden yükleyebilir miyim bilemiyorum.

**Comment by roktas** [comment]
@siyambashavva Valla bilmiyorum, başarıyla kurulum yapan çok arkadaş var.  Ya kurulumda bir yeri atlıyorsun, gözünden kaçan bir hata var, ya da dediğim gibi sisteminde sorun var.  Başarılı kurulum yapan arkadaşlarından birini bulup ondan yardım iste; birlikte kurulum yapın.

**Comment by siyambashavva** [comment]
Hocam bir şey daha soracaktım vs code u  githuba bağlayınca terminal açılmadı normalde  sorunsuz çalışıyordu bağlanmadan önce , vs code u silip tekrar yüklesem düzelir mi sizce ?

**Comment by roktas** [comment]
@siyambashavva bilmiyorum, ne desem beyhude

**Comment by siyambashavva** [comment]
Anladım hocam, bu kadar uğraştıktan sonra classroomu kurmak isterdim hiçbir arkadaşım da  benimki gibi bir sorunla karşılaşmamış ama yine de vaktinizi bana ayırdığınız için teşekkür ederim iyi geceler :( .
