### ISSUE TITLE
Sistem belirtilen dosyayı bulamıyor.  [process exited with code 4294967295 (0xffffffff)

### ISSUE THREAD

**Issue by BunyaminAkdeniz** [alaturka/windows#25]
### Adım

3 (makine yeniden başlatıldıktan sonra yapılan son kurulum)

### Hata ekranı

![image](https://user-images.githubusercontent.com/91963771/157899046-a67eb2e4-e312-4847-ae6c-5dc16a22611d.png)

### Windows sürümü

```text
Cihaz adı	DESKTOP-98K8RTH
İşlemci	Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz
Takılı RAM	16,0 GB (kullanılabilir: 15,8 GB)
Cihaz Kimliği	F7558A5A-B0F0-4538-A75E-890CF7A43F09
Ürün Kimliği	00330-80000-00000-AA849
Sistem türü	64 bit işletim sistemi, x64 tabanlı işlemci
```

### Kurulum sayısı

Evet, birden fazla kez tekrar ettim

### Kurulum Yardımı

Evet okudum, sorunum farklı: https://classroom.alaturka.dev/help/install.html

### Ayrıntılar

```wsl --distribution Classroom```komutunu çalıştırarak wsl'e root olarak giriş yapabiliyorum fakat Masaüstünde oluşan kısayol ile girmeye çalıştığımda yukarıdaki ekranda yazılı hatayı alıyorum.

**Comment by roktas** [comment]
@BunyaminAkdeniz 2'nci aşama kurulumda WSL imajı tam provizyonlanmamış ve kullanıcı oluşturulmamış sanırım.  Aşağdaıki komut için bir ekran görüntüsü alabilir miyim?

```ps1
classroom -Verbose install
```

**Comment by BunyaminAkdeniz** [comment]
```classroom -Verbose install``` komutundan sonra kurulum doğru bir şekilde tamamlandı. Masaüstündeki simgeden student@classroom olarak girebiliyorum. Komut sonrası akış: 


![image](https://user-images.githubusercontent.com/91963771/157911542-1b508eab-0edc-4cdf-a3a0-07ab6439cf21.png)
