### ISSUE TITLE
couldn't find manifest for 'vscode'

### ISSUE THREAD

**Issue by ElifAltunsu** [alaturka/windows#26]
### Adım

3 (makine yeniden başlatıldıktan sonra yapılan son kurulum)

### Hata ekranı

![error](https://user-images.githubusercontent.com/72800795/158076738-1718b388-3e9a-4c29-be4a-8f3f7db8e3a2.jpg)

### Windows sürümü

```text
Edisyon	Windows 11 Home
Sürüm	21H2
Yüklenme tarihi	‎1.‎11.‎2021
İS derlemesi	22000.556
Deneyim	Windows Özelliği Deneyim Paketi 1000.22000.556.0
```

### Kurulum sayısı

Evet, birden fazla kez tekrar ettim

### Kurulum Yardımı

Evet okudum, sorunum farklı: https://classroom.alaturka.dev/help/install.html

### Ayrıntılar

Bilgisayarımda vs code'a dair tüm kalıntıları temizledim. İlk adımı iki kere, ikinci adımı da defalarca tekrarladım ancak kurulum gerçekleşmedi.

**Comment by roktas** [comment]
İlk kurulumun tam başarılı olmamış (`extras` deposu eklenmemiş).  Aşağıdaki komutları çalıştır:

```ps1
scoop bucket rm extras
scoop bucket add extras
classroom -Verbose install
```

Bir de merak ediyorum.  Nerede kurulum yapıyorsun, evden mi yurttan mı?  Bu sorun örneğin ağ bağlantısının sorunlu olmasından ortaya çıkmış.  Aynı sorunla sürekli karşılaşıyoruz.

**Comment by ElifAltunsu** [comment]
Yurt internetiyle kurulumu gerçekleştirdim, hocam. Bu komut satırlarını kendi internetimi kullanarak komut satırına girdim. Teşekkür ederim, hocam.

**Comment by roktas** [comment]
Çözüldü mü?  Sonucu söylememişsin.

**Comment by ElifAltunsu** [comment]
İşlem uzun sürdüğünden sonucu size söylemek için bekledim hocam. Kurulum başarılı bir şekilde gerçekleşti. Yardımlarınız için çok teşekkür ederim.
