### ISSUE TITLE
Classroom Kurulumunda bu link (https://classroom.alaturka.dev/help/install.html) içerişinde aynı olmayan sorun karşılaşıyorum.

### ISSUE THREAD

**Issue by MohamedHassan1606** [alaturka/windows#27]
### Adım

1 (ön kurulum)

### Hata ekranı

iwr : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:1
+ iwr -useb https://get.classroom.alaturka.dev/classroom | iex
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

### Windows sürümü

```text
Edition : Windows 10 Home single Language 
Version:  1803 
Installed On:  28/06/2018 
OS build:  17134.1130
```

### Kurulum sayısı

Evet, birden fazla kez tekrar ettim

### Kurulum Yardımı

Evet okudum, sorunum farklı: https://classroom.alaturka.dev/help/install.html

### Ayrıntılar

Classroom Kurulumak için farklı zaman ve  ağ ortamları kullandım ancak hep aynı hata alıyorum hocam.

**Comment by roktas** [comment]
İhtimaller:

1.  Kurulum yaptığın ağ ortamında sorun var gibi gözüküyor.  Bölüm bilgisayar labına gel ve orada dene.
2. Windows kurulumunda (ne olduğunu bilemeyeceğim) sorunlar var.  Yeni bir Windows kurulumu yap.

P.S.  Bu tür iş kayıtlarına belirli bir süre içinde cevap dönün, sonucu açıklayarak.

**Comment by MohamedHassan1606** [comment]
Yarın bölüm labına gidip deneyeceğim hocam. Evet, ödevi yapmam için illaki bunu kurmam gerekmediğini farkındayım hocam. Teşekkürler
*P.S dediğiniz yerde (PostScript)tan mı bahsediyordunuz? orayı anlayamadım da hocam.

**Comment by roktas** [comment]
> P.S dediğiniz yerde (PostScript)tan mı bahsediyordunuz? orayı anlayamadım da hocam.

Evet Postscript, elim alışmış.  Türkçesi "Dipnot"

**Comment by MohamedHassan1606** [comment]
Tamam hocam, Bilgiler için sağolun.
iyi geceler diliyorum
