### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gokdenizcoban** [alaturka/windows#30]
### Adım

1 (ön kurulum)

### Hata ekranı

![resim_2022-10-16_174743781](https://user-images.githubusercontent.com/115934734/196042180-7d17dca5-df0c-4b94-8a88-f012f21188ec.png)

### Windows sürümü

```text
```Edisyon	Windows 10 Pro
Sürüm	21H2

İS derlemesi	19044.2130
Deneyim	Windows Feature Experience Pack 120.2212.4180.0



### Kurulum sayısı

Evet, birden fazla kez tekrar ettim

### Kurulum Yardımı

Evet okudum, sorunum farklı: https://classroom.alaturka.dev/help/install.html

### Ayrıntılar

Cannot add a member with the name "last_update" because a member with that name already exists. To overwrite the member anyway, add the Force parameter to your command.

**Comment by roktas** [comment]
Scoop kurulumunda bir sorunla karşılaştığını görüyorum.  Bu hata Scoop'tan da kaynaklanabilir.  Windows'da kullanıcı adın ne yazar mısın?  Veya (hata mesajına bakarak söylüyorum) sisteminde `last_update` adında bir kullanıcı mı var?  Raporladığın haliyle bir yorum yapmam güç.

**Comment by gokdenizcoban** [comment]
windows kullanıcı adım gokde ve kullanıcı olarak ortak ve bundan başka kullanıcı yok hocam [
![resim_2022-10-21_163810297](https://user-images.githubusercontent.com/115934734/197209757-d1e3aaf2-b446-4ea3-a8c1-81a750020db4.png)
![resim_2022-10-21_163832228](https://user-images.githubusercontent.com/115934734/197209820-1bf74a34-4011-445d-ab58-bb94bfebdc31.png)
