### ISSUE TITLE
GİTHUB CLASSROOM TERMİNAL DOWLOADİNG ERROR

### ISSUE THREAD

**Issue by baharallanurova** [alaturka/windows#34]
### Adım

1 (ön kurulum)

### Hata ekranı

![Ekran Görüntüsü (1)](https://user-images.githubusercontent.com/56322472/227525566-b9b28895-4e06-4161-aa65-2f1755e3b506.png)

### Windows sürümü

```text
WİNDOWS 10 PRO 22H2
```

### Kurulum sayısı

Evet, birden fazla kez tekrar ettim

### Kurulum Yardımı

Evet okudum, sorunum farklı: https://classroom.alaturka.dev/help/install.html

**Comment by beyzataylann** [comment]
@baharallanurova hatayı çözebildin mi ?

**Comment by roktas** [comment]
Classroom kurulumuyla uğraşmayın arkadaşlar, kod çok eskidi ve ilgilenecek zamanım yok.
