### ISSUE TITLE
[Invoke-WebRequest]

### ISSUE THREAD

**Issue by Gulsumgunes** [alaturka/windows#4]
### Adım

1 (ön kurulum)

### Hata ekranı

![Ekran görüntüsü 2022-03-06 141214](https://user-images.githubusercontent.com/91954993/156920649-1adb0607-578d-4827-a60e-fb3c0a44aa35.png)

### Windows sürümü

```text
Edisyon	Windows 10 Home Single Language
Sürüm	21H1
Yüklenme tarihi	‎22.‎01.‎2021
İS derlemesi	19043.1466
Deneyim	Windows Feature Experience Pack 120.2212.3920.0
```

### Ayrıntılar

Ön yükleme aşamasında powershell WebRequest komutu çağırmamı istiyor. Ne yapmalıyım?

**Comment by roktas** [comment]
Muhtemelen kurulum yapmaya çalıştığın ortamdaki ağ bazı bağlantıları kesiyor, güvenlik duvarı veya bir başka ağ kaynaklı sorun olabilir.

İşlemi tekrar etmeyi dene.  Olmuyorsa bu hatayı aldığın ağ ortamını değiştir ve örneğin laboratuvara gelerek orada dene.

**Comment by roktas** [comment]
Bu sorunun uygulamayla ilgili olduğunu düşünmediğimden kapatıyorum.
