### ISSUE TITLE
Birinci Aşama: Önyükleme HATA

### ISSUE THREAD

**Issue by eYLuLulgen** [alaturka/windows#5]
### Adım

1 (ön kurulum)

### Hata ekranı

<img width="512" alt="HATA" src="https://user-images.githubusercontent.com/92175630/156936493-258eb790-3831-4f18-8817-50e7a7acc81b.png">

### Windows sürümü

```text
Edisyon	Windows 10 Pro
Sürüm	20H2
Yüklenme tarihi	‎15.‎10.‎2021
İS derlemesi	19042.1526
Deneyim	Windows Feature Experience Pack 120.2212.4170.0
```

**Comment by roktas** [comment]
Duplicate of #2

**Comment by roktas** [comment]
#2 iş kaydını takip et (ikisi de aynı sorun) ve orada istediklerimi sen de yap.

**Comment by roktas** [comment]
@beyza-ozben bu iş kaydı sana aitse (kullanıcı adı farklı gözüküyor) kapatacağım.  Farklı bir sorun çıkmışsa onun için ayrı bir iş kaydı açarsın.

**Comment by beyza-ozben** [comment]
> @beyza-ozben bu iş kaydı sana aitse (kullanıcı adı farklı gözüküyor) kapatacağım. Farklı bir sorun çıkmışsa onun için ayrı bir iş kaydı açarsın.

Hayır hocam bana ait değil zaten ben kayıtta oluşturmadım, aynı problemi yaşadığımdan arkadaşın kaydı üzerinden iletişim kurduk

**Comment by roktas** [comment]
O halde bu kaydı kapatıyorum, sorun devam ederse tekrar açarsınız.

**Comment by eYLuLulgen** [comment]
Hocam #2 iş kaydı için dediklerinizi yaptım . O başarılı bir şekilde oldu fakat şimdi de bu hatayı veriyor.




<img width="513" alt="HATA" src="https://user-images.githubusercontent.com/92175630/157264067-d73a6000-0b93-4619-ab49-c4512b6636ec.png">
