### ISSUE TITLE
7zip hatası

### ISSUE THREAD

**Issue by suraocl** [alaturka/windows#6]
### Adım

1 (ön kurulum)

### Hata ekranı

![hata](https://user-images.githubusercontent.com/92916014/156942130-2546706a-3775-4fbe-9cd2-7b3735139e96.png)

### Windows sürümü

```text
Edisyon	Windows 10 Home
Sürüm	21H1
Yüklenme tarihi	‎17.‎08.‎2021
İS derlemesi	19043.1526
Deneyim	Windows Feature Experience Pack 120.2212.4170.0
```

### Ayrıntılar

7zip kurup denedim, silip denedim, ccleaner ile regedit temizleyip denedim her defasında aynı hata ile karşılaştım.

**Comment by roktas** [comment]
önceden başlayıp bir şekilde yarıda bıraktığın bir kurulumu devam ettirmek istemişsin gibi görünüyor.  7zip kurmana gerek yok, bunu Scoop kendisi kuruyor.  Şunu dene:

```ps1
scoop uninstall 7zip 
```

Sonrasında kurulumu tekrar  et.
