### ISSUE TITLE
Kurulum Hatası

### ISSUE THREAD

**Issue by Beyza-irem-albayrak** [alaturka/windows#7]
### Adım

1 (ön kurulum)

### Hata ekranı

![Ekran Görüntüsü (1)](https://user-images.githubusercontent.com/92369523/157023279-01dab870-9c51-4e8e-87f8-db4a0e7b5776.png)

### Windows sürümü

```text
Edisyon	Windows 11 Home Single Language
Sürüm	21H2
Yüklenme tarihi	‎5.‎03.‎2022
İS derlemesi	22000.493
Deneyim	Windows Özelliği Deneyim Paketi 1000.22000.493.0
```

### Ayrıntılar

Kurulum sırasında Classroom dosyaları kuruluyor aşamasında hata veriyor, bir kaç kez denedim aynı hatayı alıyorum ne yapmalıyım?

**Comment by roktas** [comment]
Aşağıdaki komutları verip daha sonra kurulumu tekrar eder misin?

```ps1
scoop uninstall 7zip
```
