### ISSUE TITLE
Yeniden başlatma sorunu 

### ISSUE THREAD

**Issue by yagmurgul** [alaturka/windows#8]
### Adım

2 (yeniden başlatma sırasında)

### Hata ekranı

![IMG_20220307_190604](https://user-images.githubusercontent.com/91977186/157073085-ecc8f73d-21e5-4f39-b509-9004130055f5.jpg)
![IMG_20220307_190644](https://user-images.githubusercontent.com/91977186/157073535-856301e9-3b58-4d1a-b28d-f560d94479ee.jpg)
![Uploading IMG-20220307-WA0019.jpeg…]()

### Windows sürümü

```text
Windows 10
İntel pentium quad core N3520 işlemci
500GB HDD
4GB Ram
İntel HD Graphics ekran kartı
```

### Ayrıntılar

Önyüklemeyi tamamladıktan sonra yeniden başlattım ve böyle sorun aldım.

**Comment by roktas** [comment]
Bu sorunun kurulumla ilgili olduğuna emin değilim pek.  Classroom kurulumunda sistemini bozacak bir yükleme yapılmıyor.  "Otomatik Onar" seçeneğiyle sistemini yeniden başlat ve kurulum yapılmamışsa tekrar dene.  Yalnız 4 GB RAM çok düşük, mümkünse sistemini en z 8 GB'a yükselt.

**Comment by roktas** [comment]
Mavi ekrana göre `PAGE_FAULT_IN_NONPAGED_AREA` hatası almışsın.  Olası nedenleri ve çözüm önerileri: 
 https://www.softwaretesttips.com/page-fault-in-nonpaged-area/
