### ISSUE TITLE
aria2 Hatası

### ISSUE THREAD

**Issue by eYLuLulgen** [alaturka/windows#9]
### Adım

1 (ön kurulum)

### Hata ekranı
<img width="601" alt="Ekran görüntüsü 2022-03-08 182813" src="https://user-images.githubusercontent.com/92175630/157272021-70689008-c5cd-464b-8f1c-7ebee8b7f562.png">

### Windows sürümü

```text
Edisyon	Windows 10 Pro
Sürüm	21H2
Yüklenme tarihi	‎15.‎10.‎2021
İS derlemesi	19044.1526
Deneyim	Windows Feature Experience Pack 120.2212.4170.0
```

### Ayrıntılar

Hocam hatayı gidermeye çalışmak için [https://github.com/aria2/aria2/releases/tag/release-1.36.0](url) sayfasından "aria2-1.36.0-win-64bit-build1.zip indirmeyi denedim.Fakat bir işe yaramadı.Yardımcı olur musunuz?

**Comment by roktas** [comment]
Kurulum başarısız olduğunda böyle bir düzeltme eylemine girmeniz gerekmiyor.  Hata mesajında belirtildiği gibi kurulumu tekrar etmeyi denedin mi?  Az önce bir düzeltme daha yaptım.  Kurulumu yeni baştan dene.

**Comment by eYLuLulgen** [comment]
Ön kurulum tamamlandı Hocam. Teşekkür ederim.
